# Generated by Django 5.2.7 on 2025-10-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books_published',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='list_of_books',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='added_to_site_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
